// frontend/src/customer/pages/BecomeSeller/SellerAccountForm.tsx
import { useState, useEffect } from "react";
import { Button, CircularProgress, Grid, TextField } from "@mui/material";
import { useFormik } from "formik";
import { motion, AnimatePresence } from "framer-motion";
import { useNavigate } from "react-router-dom";
import { useAppDispatch, useAppSelector } from "../../../Redux Toolkit/Store";
import { useTheme } from "../../../routes/CustomerRoutes";
import { createSeller } from "../../../Redux Toolkit/Seller/sellerAuthenticationSlice";
import CheckIcon                  from "@mui/icons-material/Check";
import PhoneIphoneIcon            from "@mui/icons-material/PhoneIphone";
import HomeWorkOutlinedIcon       from "@mui/icons-material/HomeWorkOutlined";
import AccountBalanceOutlinedIcon from "@mui/icons-material/AccountBalanceOutlined";
import StorefrontOutlinedIcon     from "@mui/icons-material/StorefrontOutlined";
import CelebrationIcon            from "@mui/icons-material/Celebration";

interface Props {
  prefillUser?: any;
}

const steps = [
  { label: "Contact",  icon: <PhoneIphoneIcon            fontSize="small" /> },
  { label: "Pickup",   icon: <HomeWorkOutlinedIcon       fontSize="small" /> },
  { label: "Bank",     icon: <AccountBalanceOutlinedIcon fontSize="small" /> },
  { label: "Business", icon: <StorefrontOutlinedIcon     fontSize="small" /> },
];

const SellerAccountForm = ({ prefillUser }: Props) => {
  const dispatch          = useAppDispatch();
  const navigate          = useNavigate();
  const { isDark }        = useTheme();
  const sellerAuth        = useAppSelector((s) => s.sellerAuth);
  const [activeStep, setActiveStep] = useState(0);
  const [showSuccess, setShowSuccess] = useState(false);

  const c = {
    text:       isDark ? "#f1f5f9"               : "#0f172a",
    textMuted:  isDark ? "#94a3b8"               : "#64748b",
    border:     isDark ? "rgba(255,255,255,0.1)" : "rgba(0,0,0,0.1)",
    bgInput:    isDark ? "#1a1a24"               : "#f8fafc",
    bgCircle:   isDark ? "#1a1a24"               : "#f1f5f9",
    accent:     "#6366f1",
    accentText: isDark ? "#a5b4fc"               : "#4f46e5",
    success:    "#22c55e",
  };

  const inputSx = {
    "& .MuiOutlinedInput-root": {
      background:   c.bgInput,
      borderRadius: "12px",
      color:        c.text,
      transition:   "all 0.2s",
      "& fieldset":             { borderColor: c.border },
      "&:hover fieldset":       { borderColor: c.accent },
      "&.Mui-focused fieldset": { borderColor: c.accent, borderWidth: 2 },
    },
    "& .MuiInputLabel-root":             { color: c.textMuted },
    "& .MuiInputLabel-root.Mui-focused": { color: c.accent },
    "& input":    { color: c.text },
    "& textarea": { color: c.text },
  };

  // ── Formik ──
  const formik = useFormik({
    enableReinitialize: true,
    initialValues: {
      mobile: prefillUser?.mobile || "",
      otp: "",
      GSTIN: "",
      pickupAddress: {
        name:     prefillUser?.fullName || "",
        mobile:   prefillUser?.mobile   || "",
        pinCode:  "", address: "", locality: "", city: "", state: "",
      },
      bankDetails: {
        accountNumber: "", ifscCode: "", accountHolderName: prefillUser?.fullName || "",
      },
      sellerName: prefillUser?.fullName || "",
      email:      prefillUser?.email    || "",
      businessDetails: {
        businessName:    "", businessEmail: prefillUser?.email || "",
        businessMobile:  prefillUser?.mobile || "",
        logo: "", banner: "", businessAddress: "",
      },
      password:   prefillUser ? "AutoGenerated@123" : "",  // logged-in users skip password
    },
    onSubmit: (values) => {
      console.log("Submitting seller:", values);
      dispatch(createSeller(values))
        .unwrap()
        .then(() => {
          setShowSuccess(true);
          setTimeout(() => navigate("/seller"), 2500);
        })
        .catch((err) => console.error(err));
    },
  });

  const isStepValid = (): boolean => {
    const v = formik.values;
    switch (activeStep) {
      case 0: return !!v.mobile && !!v.GSTIN;
      case 1: return !!v.pickupAddress.name && !!v.pickupAddress.mobile &&
                     !!v.pickupAddress.pinCode && !!v.pickupAddress.address &&
                     !!v.pickupAddress.city && !!v.pickupAddress.state;
      case 2: return !!v.bankDetails.accountNumber && !!v.bankDetails.ifscCode &&
                     !!v.bankDetails.accountHolderName;
      case 3: return !!v.businessDetails.businessName && !!v.sellerName &&
                     !!v.email && !!v.password;
      default: return false;
    }
  };

  const handleNext = () => {
    if (activeStep === steps.length - 1) {
      formik.handleSubmit();
    } else {
      setActiveStep((s) => s + 1);
    }
  };

  const handleBack = () => setActiveStep((s) => Math.max(0, s - 1));

  // ── Success screen ──
  if (showSuccess) {
    return (
      <motion.div
        initial={{ opacity: 0, scale: 0.9 }}
        animate={{ opacity: 1, scale: 1 }}
        className="text-center py-8"
      >
        <motion.div
          initial={{ scale: 0, rotate: -180 }}
          animate={{ scale: 1, rotate: 0 }}
          transition={{ type: "spring", stiffness: 200, damping: 15 }}
          className="inline-flex items-center justify-center w-20 h-20 rounded-full mb-6"
          style={{
            background: "linear-gradient(135deg, #22c55e, #16a34a)",
            boxShadow:  "0 12px 32px rgba(34,197,94,0.4)",
          }}
        >
          <CelebrationIcon sx={{ fontSize: 48, color: "#fff" }} />
        </motion.div>

        <h2 className="text-2xl font-black mb-2" style={{ color: c.text }}>
          Welcome aboard! 🎉
        </h2>
        <p className="text-sm mb-6" style={{ color: c.textMuted }}>
          Your seller account is created. Redirecting to dashboard...
        </p>

        <CircularProgress size={28} sx={{ color: c.accent }} />
      </motion.div>
    );
  }

  // ── Step content ──
  const renderStep = () => {
    switch (activeStep) {
      case 0:
        return (
          <>
            <h3 className="text-lg font-bold mb-1" style={{ color: c.text }}>
              📞 Contact Details
            </h3>
            <p className="text-sm mb-6" style={{ color: c.textMuted }}>
              How should buyers reach you?
            </p>
            <div className="space-y-4">
              <TextField fullWidth name="mobile" label="Mobile Number"
                placeholder="10-digit mobile"
                value={formik.values.mobile}
                onChange={formik.handleChange} onBlur={formik.handleBlur}
                sx={inputSx} />
              <TextField fullWidth name="GSTIN" label="GSTIN Number"
                placeholder="22AAAAA0000A1Z5"
                value={formik.values.GSTIN}
                onChange={formik.handleChange} onBlur={formik.handleBlur}
                sx={inputSx} />
            </div>
          </>
        );

      case 1:
        return (
          <>
            <h3 className="text-lg font-bold mb-1" style={{ color: c.text }}>
              📦 Pickup Address
            </h3>
            <p className="text-sm mb-6" style={{ color: c.textMuted }}>
              Where should we collect your products?
            </p>
            <Grid container spacing={2}>
              <Grid size={12}>
                <TextField fullWidth name="pickupAddress.name" label="Contact Name"
                  value={formik.values.pickupAddress.name}
                  onChange={formik.handleChange} onBlur={formik.handleBlur}
                  sx={inputSx} />
              </Grid>
              <Grid size={6}>
                <TextField fullWidth name="pickupAddress.mobile" label="Mobile"
                  value={formik.values.pickupAddress.mobile}
                  onChange={formik.handleChange} onBlur={formik.handleBlur}
                  sx={inputSx} />
              </Grid>
              <Grid size={6}>
                <TextField fullWidth name="pickupAddress.pinCode" label="Pincode"
                  value={formik.values.pickupAddress.pinCode}
                  onChange={formik.handleChange} onBlur={formik.handleBlur}
                  sx={inputSx} />
              </Grid>
              <Grid size={12}>
                <TextField fullWidth name="pickupAddress.address" label="Street Address"
                  value={formik.values.pickupAddress.address}
                  onChange={formik.handleChange} onBlur={formik.handleBlur}
                  sx={inputSx} />
              </Grid>
              <Grid size={12}>
                <TextField fullWidth name="pickupAddress.locality" label="Locality"
                  value={formik.values.pickupAddress.locality}
                  onChange={formik.handleChange} onBlur={formik.handleBlur}
                  sx={inputSx} />
              </Grid>
              <Grid size={6}>
                <TextField fullWidth name="pickupAddress.city" label="City"
                  value={formik.values.pickupAddress.city}
                  onChange={formik.handleChange} onBlur={formik.handleBlur}
                  sx={inputSx} />
              </Grid>
              <Grid size={6}>
                <TextField fullWidth name="pickupAddress.state" label="State"
                  value={formik.values.pickupAddress.state}
                  onChange={formik.handleChange} onBlur={formik.handleBlur}
                  sx={inputSx} />
              </Grid>
            </Grid>
          </>
        );

      case 2:
        return (
          <>
            <h3 className="text-lg font-bold mb-1" style={{ color: c.text }}>
              🏦 Bank Details
            </h3>
            <p className="text-sm mb-6" style={{ color: c.textMuted }}>
              Where should we send your earnings?
            </p>
            <div className="space-y-4">
              <TextField fullWidth name="bankDetails.accountNumber" label="Account Number"
                value={formik.values.bankDetails.accountNumber}
                onChange={formik.handleChange} onBlur={formik.handleBlur}
                sx={inputSx} />
              <TextField fullWidth name="bankDetails.ifscCode" label="IFSC Code"
                value={formik.values.bankDetails.ifscCode}
                onChange={formik.handleChange} onBlur={formik.handleBlur}
                sx={inputSx} />
              <TextField fullWidth name="bankDetails.accountHolderName" label="Account Holder Name"
                value={formik.values.bankDetails.accountHolderName}
                onChange={formik.handleChange} onBlur={formik.handleBlur}
                sx={inputSx} />
            </div>
            <div
              className="mt-4 p-3 rounded-xl flex items-start gap-2 text-xs"
              style={{
                background: "rgba(34,197,94,0.08)",
                border:     "1px solid rgba(34,197,94,0.2)",
                color:      c.success,
              }}
            >
              🔒 Bank details are encrypted and secure
            </div>
          </>
        );

      case 3:
        return (
          <>
            <h3 className="text-lg font-bold mb-1" style={{ color: c.text }}>
              🏪 Business Details
            </h3>
            <p className="text-sm mb-6" style={{ color: c.textMuted }}>
              Final step — tell us about your business
            </p>
            <div className="space-y-4">
              <TextField fullWidth name="businessDetails.businessName" label="Business Name"
                value={formik.values.businessDetails.businessName}
                onChange={formik.handleChange} onBlur={formik.handleBlur}
                sx={inputSx} />
              <TextField fullWidth name="sellerName" label="Your Full Name"
                value={formik.values.sellerName}
                onChange={formik.handleChange} onBlur={formik.handleBlur}
                disabled={!!prefillUser?.fullName}
                sx={inputSx} />
              <TextField fullWidth type="email" name="email" label="Email Address"
                value={formik.values.email}
                onChange={formik.handleChange} onBlur={formik.handleBlur}
                disabled={!!prefillUser?.email}
                sx={inputSx} />
              {!prefillUser && (
                <TextField fullWidth type="password" name="password" label="Password"
                  value={formik.values.password}
                  onChange={formik.handleChange} onBlur={formik.handleBlur}
                  sx={inputSx} />
              )}
              {prefillUser && (
                <div
                  className="text-xs px-3 py-2 rounded-lg"
                  style={{
                    background: "rgba(99,102,241,0.08)",
                    color:      c.accentText,
                  }}
                >
                  ✓ Using your existing Nexkart account credentials
                </div>
              )}
            </div>
          </>
        );

      default: return null;
    }
  };

  return (
    <div>
      {/* ═══════ Stepper ═══════ */}
      <div className="flex items-center justify-between mb-8 relative px-2">
        {steps.map((step, i) => {
          const isActive    = i === activeStep;
          const isCompleted = i < activeStep;

          return (
            <div key={step.label} className="flex flex-col items-center flex-1 relative">
              {i > 0 && (
                <motion.div
                  initial={false}
                  animate={{
                    background: isCompleted || isActive
                      ? "linear-gradient(90deg, #6366f1, #8b5cf6)"
                      : c.border,
                  }}
                  transition={{ duration: 0.3 }}
                  className="absolute top-5 right-1/2 w-full h-0.5 z-0"
                />
              )}

              <motion.div
                initial={false}
                animate={{ scale: isActive ? 1.1 : 1 }}
                transition={{ type: "spring", stiffness: 300, damping: 20 }}
                className="w-10 h-10 rounded-full flex items-center justify-center relative z-10"
                style={{
                  background: isActive || isCompleted
                    ? "linear-gradient(135deg, #6366f1, #8b5cf6)"
                    : c.bgCircle,
                  border:    isActive || isCompleted ? "none" : `2px solid ${c.border}`,
                  boxShadow: isActive ? "0 4px 14px rgba(99,102,241,0.4)" : "none",
                  color:     isActive || isCompleted ? "#fff" : c.textMuted,
                }}
              >
                <AnimatePresence mode="wait">
                  {isCompleted ? (
                    <motion.div
                      key="check"
                      initial={{ scale: 0, rotate: -90 }}
                      animate={{ scale: 1, rotate: 0 }}
                      exit={{ scale: 0 }}
                    >
                      <CheckIcon sx={{ fontSize: 16 }} />
                    </motion.div>
                  ) : (
                    <motion.div
                      key="icon"
                      initial={{ scale: 0 }}
                      animate={{ scale: 1 }}
                      exit={{ scale: 0 }}
                    >
                      {step.icon}
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>

              <p
                className="text-[10px] font-bold uppercase tracking-wider mt-2 text-center transition-colors"
                style={{ color: isActive ? c.accentText : c.textMuted }}
              >
                {step.label}
              </p>
            </div>
          );
        })}
      </div>

      {/* ═══════ Step content ═══════ */}
      <AnimatePresence mode="wait">
        <motion.div
          key={activeStep}
          initial={{ opacity: 0, x: 30, filter: "blur(4px)" }}
          animate={{ opacity: 1, x: 0,  filter: "blur(0px)" }}
          exit={{   opacity: 0, x: -30, filter: "blur(4px)" }}
          transition={{ duration: 0.3, ease: "easeOut" }}
          className="min-h-[320px]"
        >
          {renderStep()}
        </motion.div>
      </AnimatePresence>

      {/* ═══════ Buttons ═══════ */}
      <div className="flex items-center justify-between gap-3 mt-8">
        <Button
          disabled={activeStep === 0}
          onClick={handleBack}
          variant="outlined"
          sx={{
            py: "10px", px: 3, borderRadius: "12px",
            fontWeight: 700, textTransform: "none",
            color: c.text, borderColor: c.border,
            transition: "all 0.2s",
            "&:hover": { borderColor: c.accent, background: "rgba(99,102,241,0.05)" },
            "&:disabled": { borderColor: c.border, color: c.textMuted, opacity: 0.4 },
          }}
        >
          ← Back
        </Button>

        <Button
          disabled={sellerAuth.loading || !isStepValid()}
          onClick={handleNext}
          variant="contained"
          sx={{
            py: "10px", px: 4, borderRadius: "12px",
            fontWeight: 800, textTransform: "none",
            background: "linear-gradient(135deg, #6366f1, #8b5cf6)",
            boxShadow:  "0 6px 20px rgba(99,102,241,0.35)",
            transition: "all 0.2s",
            "&:hover":  { background: "linear-gradient(135deg, #4f46e5, #7c3aed)", transform: "translateY(-1px)" },
            "&:disabled": {
              background: isDark ? "rgba(255,255,255,0.06)" : "rgba(0,0,0,0.06)",
              color:      isDark ? "rgba(255,255,255,0.25)" : "rgba(0,0,0,0.3)",
              boxShadow:  "none",
            },
          }}
        >
          {sellerAuth.loading
            ? <CircularProgress size={20} sx={{ color: "white" }} />
            : activeStep === steps.length - 1
            ? "Create Account ✨"
            : "Continue →"}
        </Button>
      </div>

      <p className="text-center text-xs mt-4" style={{ color: c.textMuted }}>
        Step {activeStep + 1} of {steps.length}
      </p>
    </div>
  );
};

export default SellerAccountForm;